name: "Composer Lint"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/composer-lint.yml
      - composer.json
  push:
    branches:
      - "*.x"
    paths:
      - .github/workflows/composer-lint.yml
      - composer.json

jobs:
  composer-lint:
    name: "Composer Lint"
    uses: "doctrine/.github/.github/workflows/composer-lint.yml@3.0.0"
